/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloClient: typeof import('./src/components/HelloClient.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./src/components/ui/button/UiButton.vue')['default']
    UiLanguageToggle: typeof import('./src/components/ui/language-toggle/UiLanguageToggle.vue')['default']
    UiSonner: typeof import('./src/components/ui/sonner/UiSonner.vue')['default']
  }
}
